#ifndef __FLOAT_H
#define __FLOAT_H

#define HUGE_VAL	DBL_MAX

#define	DBL_DIG			7
#define	DBL_EPSILON 	1.192092896e-7f
#define DBL_MANT_DIG	24
#define DBL_MAX			3.402823466e+38f
#define	DBL_MAX_10_EXP	38
#define DBL_MAX_EXP		127
#define	DBL_MIN			1.175494351e-38f
#define	DBL_MIN_10_EXP	(-38)
#define DBL_MIN_EXP		(-127)

#define	FLT_DIG			7
#define	FLT_EPSILON 	1.192092896e-7f
#define FLT_MANT_DIG	24
#define FLT_MAX			3.402823466e+38f
#define	FLT_MAX_10_EXP	38
#define FLT_MAX_EXP		127
#define	FLT_MIN			1.175494351e-38f
#define	FLT_MIN_10_EXP	(-38)
#define FLT_MIN_EXP		(-127)

#define FLT_RADIX		2
#define FLT_ROUNDS		(-1)

#endif
