#ifndef __LIMIT_H
#define __LIMIT_H
#define CHAR_BIT	8
#define CHAR_MAX	UCHAR_MAX
#define CHAR_MIN	UCHAR_MIN
#define INT_MAX		32767
#define INT_MIN		-32768
#define SCHAR_MAX	127
#define SCHAR_MIN	-128
#define SHRT_MAX	INT_MAX
#define SHRT_MIN	INT_MIN
#define UCHAR_MAX	255
#define UCHAR_MIN	0
#define UINT_MAX	65535u
#define UINT_MIN	0
#define USHRT_MAX	UINT_MAX
#define USHRT_MIN	0
#define LONG_MAX	 2147483647L
#define LONG_MIN	(-2147483647L-1)
#define ULONG_MAX	4294967295UL
#define ULONG_MIN	0
#endif
